[project]
name = "packseed"
version = "0.1.0"
description = "The Minecraft pack creator."
authors = ["FoxedDev"]
readme = "README.md"
license = "LICENSE"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.3",
    "prompt-toolkit>=3.0.52",
    "requests>=2.33.1",
    "rich-click>=1.9.7",
    "ruff>=0.15.11",
    "send2trash>=2.1.0",
]

[tool.ruff.lint]
extend-select = ["I"]
