[build-system]
requires = ["uv_build >= 0.11.7, <0.12.0"]
build-backend = "uv_build"

[project]
name = "bonemeal"
version = "0.1.0"
dependencies = [
    "click>=8.3.3",
    "prompt-toolkit>=3.0.52",
    "requests>=2.33.1",
    "rich-click>=1.9.7",
    "ruff>=0.15.11",
    "send2trash>=2.1.0",
]
requires-python = ">=3.14"
authors = [{ name = "FoxedDev", email = "foxed.dev@gmail.com" }]
description = "The Minecraft pack manager."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["minecraft", "pack", "management", "cli"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Build Tools ",
]

[project.urls]
Repository = "https://github.com/foxeddev/bonemeal.git"
"Bug Tracker" = "https://github.com/foxeddev/bonemeal/issues"
Changelog = "https://github.com/foxeddev/bonemeal/releases"

[project.scripts]
bonemeal = "bonemeal.__main__:main"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "PLR0913", # too many arguments
    "TD003",   # issue link for todos
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]
